%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5
@STRING(scn="Science") @STRING(nat="Nature") @string{ANN = "Annals
of Physics"} @string{LOWTEMP = "J. Low. Temp. Phys."} @string{IJMP =
"Int. J. Mod. Phys. B"} @string{MPL = "Mod. Phys. Lett. B"}
@string{NP = "Nucl. Phys. B"} @string{JPHYS1 = "J. Phys. Soc.
Japan"} @string{JPHYS2 = "J. Physique"} @string{JPHYSA = "J. Phys.
A"} @string{JPHYSB = "J. Phys. B"} @string{JPHYSC = "J. Phys. C"}
@string{JAP = "J. Appl. Phys."} @string{PLA = "Phys. Lett. A"}
@string{PLB = "Phys. Lett. B"} @string{PRL = "Phys. Rev. Lett."}
@string{PHYSF = "Phys. Fluids"} @string{PHYSR = "Phys. Rep."}
@string{PRA = "Phys. Rev. A "} @string{PRB = "Phys. Rev. B "}
@string{PRC = "Phys. Rev. C "} @string{PRD = "Phys. Rev. D "}
@string{PR = "Phys. Rev. "} @string{PROG = "Prog. Theor. Phys. "}
@string{PHYSS = "Phys. Scripta"} @string{PHYST = "Phys. Today"}
@string{RMP = "Rev. Mod. Phys."} @string{ZPHY = "Z. Phys. "}
@string{epl = "Europhys. Lett. "}

%%%%%%%%%%for DMS
@book{Chien2007,
    title = {Transition Metal-Doped Sb2Te3 and Bi2Te3 Diluted Magnetic Semiconductors },
    publisher = {A dissertation submitted in partial fulfillment of the requirements for
    the degree of Doctor of Philosophy(Applied Physics) in The University of Michigan},
    Author = {Chien, Yi-Jiunn},
    year = {2007}
}
@article{Chien2005,
  title={{Growth and transport properties of Sb2- xVxTe3 thin films on sapphire substrates}},
  author={Chien, Y.J. and Zhou, Z. and Uher, C.},
  journal={Journal of Crystal Growth},
  volume={283},
  number={3-4},
  pages={309--314},
  year={2005},
  publisher={Elsevier}
}
 